<?php
///////////////////////////////////////////////////////////////////////////////
//GUS - Groups in a University Setting
//Author: Colby Blair
///////////////////////////////////////////////////////////////////////////////

function page_header($vt) {
return("
<html>
<head>
<title>GUS Default Visual Template</title>
<link rel=\"stylesheet\" type=\"text/css\" href=\"templates/" . $vt . "/template.css\" />
</head>
<body>
<!-- Banner and Nav -->
	<div id=\"spreader_top\">
		<div id=\"links\">

			<!-- Username that links to profile + new mail icon -->
			<div id=\"links_left\">
			Greetings <u>Scott</u>, <img src=\"mail.png\">
			</div>

			<!-- At some point these need to be finalized -->
			<div id=\"links_right\">
			Messages | Forums | Edit Groups | Home | Logout
			</div>
		</div>
	</div>

<!--
<h1 id=\"header_element\">GUS</h1>

<ul id=\"links\">
 <li><a href=\"index.php?page=home\">Home</a></li>
 <li><a href=\"index.php?page=about\">About</a></li>
 <li><a href=\"add-page.php?page=add-page.php\">Add A Page</a></li>
 <li><a href=\"add-user.php?page=add-user.php\">Add A User</a></li>
 <li><a href=\"add-group.php?page=add-group.php\">Add A Group</a></li>
 <li><a href=\"add-group-member.php?page=add-group-member.php\">Add A Group Member</a></li>
 <li>Login</li>
 <li><a href=\"registration.php?page=registration.php\">Register</a></li>
</ul> /-->
<!-- Autogenerated List of Groups by Scott linked by Cindy -->
		<div id=\"group_column\">
			<ul>
				<li>Autogenerated</li>
				<li>U of I 1</li>
				<li>U of I 2 </li>
				<li>U of I 3</li>
				<li>U of I 4</li>
				<li>U of I 5</li>
				<li>U of I 6</li>
				<li>U of I 7</li>
				<li id=\"group_column_current\">Current Page</li>
				<li>U of I 9</li>
				<li>U of I 10</li>
				<li>A longer name!!</li>
			</ul>
				<div id=\"group_controls\">
				<img src=\"add_group2.png\"><img src=\"remove_group2.png\">
			</div>
		</div>
<div id=\"content\">
");
}

function page_footer($extra_content) {
return("
$extra_content
</div>
</body>
</html>
");
}

?>
